name: Alt Text Suggestor

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-caption:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Check for inline images with no alt text and generate suggestions accordingly
        run: python main.py
        env:
          AZURE_COGNITIVE_SERVICES_KEY: ${{ secrets.AZURE_COGNITIVE_SERVICES_KEY }}
          AZURE_COGNITIVE_SERVICES_ENDPOINT: ${{ secrets.AZURE_COGNITIVE_SERVICES_ENDPOINT }}
