name: Alt Text Suggestor

on:
  pull_request:
    branches: [main]

jobs:
  check_alt_text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run alt text suggestor
      env:
        AZURE_COGNITIVE_SERVICES_KEY: ${{ secrets.AZURE_COGNITIVE_SERVICES_KEY }}
        AZURE_COGNITIVE_SERVICES_ENDPOINT: ${{ secrets.AZURE_COGNITIVE_SERVICES_ENDPOINT }}
      run: |
        python main.py | tee output.txt

    - name: Check for main.py output (no output == all images good)
      run: |
        if [ -s output.txt ]; then
          echo "There are images with missing alt text in README.md"
          cat output.txt
          exit 1
        else
          echo "All images have alt text, pull request will succeed"
        fi
